USE [master]
GO

/****** Object:  Database [LittleLozon]    Script Date: 30.01.2024 17:55:09 ******/
CREATE DATABASE [LittleLozon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LittleLozon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVERLEARN\MSSQL\DATA\LittleLozon.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LittleLozon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVERLEARN\MSSQL\DATA\LittleLozon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LittleLozon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LittleLozon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LittleLozon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LittleLozon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LittleLozon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LittleLozon] SET ARITHABORT OFF 
GO

ALTER DATABASE [LittleLozon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LittleLozon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LittleLozon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LittleLozon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LittleLozon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LittleLozon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LittleLozon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LittleLozon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LittleLozon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LittleLozon] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LittleLozon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LittleLozon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LittleLozon] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [LittleLozon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LittleLozon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LittleLozon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LittleLozon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LittleLozon] SET RECOVERY FULL 
GO

ALTER DATABASE [LittleLozon] SET  MULTI_USER 
GO

ALTER DATABASE [LittleLozon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LittleLozon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LittleLozon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LittleLozon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LittleLozon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LittleLozon] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LittleLozon] SET QUERY_STORE = ON
GO

ALTER DATABASE [LittleLozon] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [LittleLozon] SET  READ_WRITE 
GO


