USE [LittleLozon]
GO

/****** Object:  Table [dbo].[Route]    Script Date: 30.01.2024 18:04:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Route](
	[ID] [BIGINT] NOT NULL,
	[Name] [VARCHAR](255) NOT NULL,
	[Descript] [VARCHAR](255) NULL,
	[MinPlaceID] [BIGINT] NOT NULL,
	[MaxPlaceID] [BIGINT] NOT NULL,
	[OwnerObjectID] [BIGINT] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Route]  WITH CHECK ADD FOREIGN KEY([MaxPlaceID])
REFERENCES [dbo].[Place] ([ID])
GO

ALTER TABLE [dbo].[Route]  WITH CHECK ADD FOREIGN KEY([MinPlaceID])
REFERENCES [dbo].[Place] ([ID])
GO

ALTER TABLE [dbo].[Route]  WITH CHECK ADD FOREIGN KEY([OwnerObjectID])
REFERENCES [dbo].[Contract] ([ID])
GO


