USE [LittleLozon]
GO

/****** Object:  Table [dbo].[Contractor]    Script Date: 30.01.2024 18:02:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contractor](
	[ID] [BIGINT] NOT NULL,
	[Name] [VARCHAR](255) NOT NULL,
	[INN] [VARCHAR](255) NULL,
	[KPP] [VARCHAR](255) NULL,
	[LegalAddressStr] [VARCHAR](255) NULL,
	[ShortName] [VARCHAR](255) NULL,
	[Descript] [VARCHAR](255) NULL,
	[ContractorType] [VARCHAR](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


