USE [LittleLozon]
GO

/****** Object:  Table [dbo].[Place]    Script Date: 30.01.2024 18:04:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Place](
	[ID] [BIGINT] NOT NULL,
	[Barcode] [VARCHAR](50) NULL,
	[ContractID] [BIGINT] NULL,
	[OwnerObjectID] [BIGINT] NULL,
	[Name] [VARCHAR](255) NOT NULL,
	[Descript] [VARCHAR](255) NULL,
	[PlaceType] [VARCHAR](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Place]  WITH CHECK ADD FOREIGN KEY([ContractID])
REFERENCES [dbo].[Contract] ([ID])
GO

ALTER TABLE [dbo].[Place]  WITH CHECK ADD FOREIGN KEY([OwnerObjectID])
REFERENCES [dbo].[Place] ([ID])
GO


